FROM        viatcheslavmogilevsky/ruby-common
MAINTAINER  V. Mogilevksy "https://github.com/viatcheslavmogilevsky"

# Install ruby and bundler
RUN bash -l -c 'rbenv install 2.1.2'
RUN bash -l -c 'rbenv global 2.1.2'
RUN bash -l -c 'rbenv rehash'
RUN bash -l -c 'gem install bundler'






